export const onboardingStepKeys = ['prepare', 'identity', 'face', 'contact', 'application', 'review', 'track']

export const governorateOptions = [
  'Cairo',
  'Alexandria',
  'Port Said',
  'Suez',
  'Damietta',
  'Dakahlia',
  'Sharqia',
  'Qalyubia',
  'Kafr El Sheikh',
  'Gharbia',
  'Monufia',
  'Beheira',
  'Ismailia',
  'Giza',
  'Beni Suef',
  'Faiyum',
  'Minya',
  'Asyut',
  'Sohag',
  'Qena',
  'Aswan',
  'Luxor',
  'Red Sea',
  'New Valley',
  'Matrouh',
  'North Sinai',
  'South Sinai',
  'Born outside Egypt',
  'Other',
]

export const selectOptions = {
  yesNo: ['Yes', 'No'],
  customerType: ['Individuals'],
  gender: ['Male', 'Female'],
  correspondenceAddressSource: ['Residence address from ID document', 'Alternate residence address', 'Employer address'],
  correspondenceLanguage: ['Arabic', 'English'],
  deliveryMethod: ['Regular mail', 'Branch pickup', 'Employee visit'],
  maritalStatus: ['Single', 'Married', 'Divorced', 'Widowed'],
  housingNature: ['Owned', 'Rented', 'Family residence', 'Company housing'],
  rentalType: ['New rent', 'Old rent', 'Furnished rent', 'Not applicable'],
  educationStatus: ['No formal education', 'Secondary', 'Bachelor degree', 'Postgraduate'],
  employmentNature: ['Employee', 'Self-employed', 'Business owner', 'Retired', 'Student', 'Not employed'],
  employmentStatus: ['Temporary', 'Permanent'],
  jobGrade: ['Staff', 'Supervisor', 'Manager', 'Senior manager', 'Executive'],
  currentPosition: ['Specialist', 'Supervisor', 'Manager', 'Director', 'Business owner', 'Other'],
  annualIncomeBracket: ['Less than EGP 120,000', 'EGP 120,000-300,000', 'EGP 300,001-600,000', 'More than EGP 600,000'],
  accountType: ['Current account', 'Savings account'],
  accountCurrency: ['Egyptian Pound'],
  statementFrequency: ['Monthly', 'Quarterly', 'Semi-annually', 'Annually'],
  statementDeliveryAddress: ['Correspondence address', 'ID residence address', 'Employer address'],
  foreignCurrencyTransferHandling: [
    'Open a new account in the transfer currency and deduct applicable fees',
    'Convert the transfer into the currency of an existing account at the announced rate',
  ],
}

export const accountTransactionTypeOptions = [
  'Cash',
  'Cash and cheques',
  'Cash deposit by third parties',
  'Transfers from third parties',
  'Other',
]

export const additionalIdentityFields = [
  { name: 'customerType', label: 'Customer type', type: 'select', options: selectOptions.customerType },
  { name: 'firstNameAr', label: 'First name in Arabic', required: true, ocr: true },
  { name: 'middleNameAr', label: 'Middle name in Arabic', required: true, ocr: true },
  { name: 'lastNameAr', label: 'Last name in Arabic', required: true, ocr: true },
  { name: 'gender', label: 'Gender', type: 'select', options: selectOptions.gender, ocr: true },
  { name: 'nationalIdExpiryDate', label: 'National ID expiry date', type: 'date', ocr: true },
  { name: 'nationalIdIssueDate', label: 'National ID issue date (year and month)', type: 'month', required: true, ocr: true },
  { name: 'nationalIdCardPrintedNumber', label: 'Printed number on ID card', required: true, ocr: true },
  { name: 'placeOfBirth', label: 'Place of birth', type: 'select', options: governorateOptions, required: true, ocr: true },
  { name: 'idResidenceAddressAr', label: 'Residence address from ID in Arabic', maxLength: 50, required: true, ocr: true },
  { name: 'alternateResidenceAddressAr', label: 'Alternate residence address in Arabic', maxLength: 50 },
]

export const correspondenceFields = [
  { name: 'correspondenceAddressSource', label: 'Correspondence address', type: 'select', options: selectOptions.correspondenceAddressSource },
  { name: 'correspondenceLanguage', label: 'Correspondence language', type: 'select', options: selectOptions.correspondenceLanguage },
  { name: 'landlineNumber', label: 'Landline number including area code', inputMode: 'tel' },
  { name: 'deliveryMethod', label: 'Delivery method', type: 'select', options: selectOptions.deliveryMethod },
]

export const socialFields = [
  { name: 'maritalStatus', label: 'Marital status', type: 'select', options: selectOptions.maritalStatus },
  { name: 'numberOfDependents', label: 'Number of dependents', type: 'number', min: '0' },
  { name: 'housingNature', label: 'Housing nature', type: 'select', options: selectOptions.housingNature },
  { name: 'rentalType', label: 'Rental type', type: 'select', options: selectOptions.rentalType },
  { name: 'educationStatus', label: 'Education status', type: 'select', options: selectOptions.educationStatus },
]

export const employmentFields = [
  { name: 'employmentNature', label: 'Employment nature', type: 'select', options: selectOptions.employmentNature },
  { name: 'employerName', label: 'Employer name', required: true },
  { name: 'employmentStartDate', label: 'Employment start date', type: 'date' },
  { name: 'employerAddress', label: 'Employer address', maxLength: 50 },
  { name: 'monthlySalary', label: 'Monthly salary', type: 'number', min: '0' },
  { name: 'employmentStatus', label: 'Employment status', type: 'select', options: selectOptions.employmentStatus },
  { name: 'jobGrade', label: 'Job grade', type: 'select', options: selectOptions.jobGrade },
  { name: 'employerPhone', label: 'Employer phone', inputMode: 'tel' },
  { name: 'otherIncomeSources', label: 'Other income sources' },
  { name: 'currentPosition', label: 'Current position', type: 'select', options: selectOptions.currentPosition, required: true },
  { name: 'employerFax', label: 'Employer fax' },
  { name: 'annualIncomeBracket', label: 'Annual income bracket', type: 'select', options: selectOptions.annualIncomeBracket },
]

export const accountPreferenceFields = [
  { name: 'accountType', label: 'Account type', type: 'select', options: selectOptions.accountType },
  { name: 'accountCurrency', label: 'Account currency', type: 'select', options: selectOptions.accountCurrency, disabled: true },
  { name: 'accountOpeningPurposeAr', label: 'Purpose of opening the account in Arabic', required: true },
  { name: 'statementFrequency', label: 'Statement frequency', type: 'select', options: selectOptions.statementFrequency, required: true },
  { name: 'statementDeliveryAddress', label: 'Statement delivery address', type: 'select', options: selectOptions.statementDeliveryAddress },
  { name: 'cardPrintedName', label: 'Name to print on card', minLength: 7, maxLength: 20, required: true },
  { name: 'foreignCurrencyTransferHandling', label: 'Foreign-currency transfer handling', type: 'select', options: selectOptions.foreignCurrencyTransferHandling },
  { name: 'isBeneficialOwner', label: 'Are you the beneficial owner?', type: 'select', options: selectOptions.yesNo },
  { name: 'hasOtherBankAccountsOrCards', label: 'Do you have accounts/cards with other banks?', type: 'select', options: selectOptions.yesNo, required: true },
]

export const initialForm = {
  eligibility: {
    newCustomer: false,
    resident: false,
    age: false,
    validId: false,
  },
  nationalId: '',
  dateOfBirth: '',
  fullName: '',
  customerType: 'Individuals',
  firstNameAr: '',
  middleNameAr: '',
  lastNameAr: '',
  gender: '',
  nationalIdExpiryDate: '',
  nationalIdIssueDate: '',
  nationalIdCardPrintedNumber: '',
  placeOfBirth: '',
  idResidenceAddressAr: '',
  alternateResidenceAddressAr: '',
  hasSpecialNeeds: false,
  hasOtherNationality: false,
  hasResidencyInOtherCountry: false,
  mobile: '',
  smsOtp: '',
  email: '',
  emailConfirmation: '',
  emailOtp: '',
  correspondenceAddressSource: 'Residence address from ID document',
  correspondenceLanguage: 'Arabic',
  landlineNumber: '',
  deliveryMethod: 'Regular mail',
  governorate: '',
  address: '',
  maritalStatus: '',
  numberOfDependents: '',
  housingNature: '',
  rentalType: '',
  educationStatus: '',
  employment: '',
  income: '',
  employmentNature: '',
  employerName: '',
  employmentStartDate: '',
  employerAddress: '',
  monthlySalary: '',
  isOrWasPep: false,
  employmentStatus: '',
  jobGrade: '',
  employerPhone: '',
  otherIncomeSources: '',
  currentPosition: '',
  employerFax: '',
  annualIncomeBracket: '',
  accountType: '',
  accountCurrency: 'Egyptian Pound',
  accountOpeningPurposeAr: '',
  statementFrequency: '',
  statementDeliveryAddress: '',
  accountTransactionTypes: ['Cash', 'Transfers from third parties'],
  cardPrintedName: '',
  foreignCurrencyTransferHandling: 'Convert the transfer into the currency of an existing account at the announced rate',
  smsAlertSubscription: true,
  secureCodeSubscription: true,
  isBeneficialOwner: 'Yes',
  hasOtherBankAccountsOrCards: '',
  incomeProofDocument: null,
  method: '',
  selectedBranch: '',
  appointmentDate: '',
  appointmentSlot: '',
  terms: false,
  faceVerification: null,
}
